### ISSUE TITLE
Great project, any traction?

### ISSUE THREAD

**Issue by ydennisy** [Nameles-Org/Nameles#5]
Hello,
I love the idea of this project but it seems adoption is low - have you stopped any development?
Also did you have a business idea in mind for this project?
Best,
Dennis

**Comment by mikkokotila** [comment]
@ydennisy thanks so  much :) No, we did not stop development. We have been working on a temporal dimension to be added to the scoring mechanism. It should be available soon. 

In terms of business idea, the goal is to keep improving it and slowly see it adopted by the industry. There are some adopters / trials, including some of the bigger companies in the space. 

Because this is completely non-profit activity, things are slow. If we had more financial support in terms of donations from the industry, it would be possible to move faster as we could invest into marketing etc. 

The other thing that would be really useful is code contributors to the repo.
